namespace ClaudeWeb.Services.Watchdog;

/// <summary>
/// The pure parts of the harness keep-alive watchdog (fleet task c96de7ae): the OS-level
/// state mapping and the generated scripts. Kept framework-free so they unit-test without
/// a host — the controller does the privileged I/O (probe the task, write the scripts,
/// try to register, surface the exact elevated command on "Access is denied").
///
/// The mechanism is a Windows Scheduled Task that survives the harness dying: it runs a
/// small watchdog loop at BOOT and at LOGON, restarts that loop on failure, and the loop
/// health-checks the harness port and relaunches the harness (detached, the swap.ps1 way)
/// whenever it is down. Precedents: swap.ps1 / arm-rollback.ps1 (Register-ScheduledTask).
/// </summary>
public static class WatchdogPlan
{
    /// <summary>The scheduled task's name — the single identity the probe/create/remove key on.</summary>
    public const string TaskName = "ClaudeWebKeepAlive";

    /// <summary>Keep-alive state for the status strip. Derived from a REAL probe of the OS
    /// task (does it exist, is it enabled), never a guess.
    ///   unsupported — not a Windows host.
    ///   not_set_up  — the task does not exist; offer one-click create.
    ///   healthy     — the task exists and is enabled.
    ///   error       — the task exists but is disabled, or the probe failed.</summary>
    public static string StateOf(bool supported, bool exists, bool enabled) =>
        !supported ? "unsupported"
        : !exists ? "not_set_up"
        : enabled ? "healthy"
        : "error";

    /// <summary>The watchdog loop written to disk at create time, with the concrete harness
    /// exe + port baked in so it never depends on the repo being present. Health-checks the
    /// port; relaunches the harness detached when it is down; loops forever. The task's
    /// restart-on-failure covers this script itself crashing.</summary>
    public static string WatchdogScript(string exePath, int port) =>
        "# ClaudeWeb keep-alive watchdog (fleet task c96de7ae). Started at boot AND logon by\n" +
        "# the " + TaskName + " scheduled task; loops forever, and whenever the harness port is\n" +
        "# down it relaunches the harness DETACHED (the same run-bin exe swap.ps1 restarts).\n" +
        "# Generated by the harness; edit the scheduled task, not this file.\n" +
        "$ErrorActionPreference = 'SilentlyContinue'\n" +
        "$exe = '" + PsQuote(exePath) + "'\n" +
        "$port = " + port + "\n" +
        "$runDir = Split-Path -Parent $exe\n" +
        "while ($true) {\n" +
        "  $alive = $false\n" +
        "  try { if ((Invoke-WebRequest \"http://localhost:$port/api/health\" -TimeoutSec 4 -UseBasicParsing).StatusCode -eq 200) { $alive = $true } } catch { $alive = $false }\n" +
        "  if (-not $alive -and (Test-Path $exe)) {\n" +
        "    Start-Process -FilePath $exe -WorkingDirectory $runDir -WindowStyle Hidden\n" +
        "    Start-Sleep -Seconds 20\n" +
        "  } else {\n" +
        "    Start-Sleep -Seconds 15\n" +
        "  }\n" +
        "}\n";

    /// <summary>The installer written to disk at create time: registers the scheduled task
    /// with an AtStartup AND an AtLogon trigger, restart-on-failure, highest privileges, run
    /// as the current interactive user. Registering a boot-trigger task requires elevation,
    /// so this is ALSO what the Operator runs elevated when the harness itself is denied.</summary>
    public static string InstallScript(string watchdogPath) =>
        "# Installs the " + TaskName + " scheduled task (fleet task c96de7ae): runs the harness\n" +
        "# watchdog at BOOT and at LOGON, restarts it on failure, highest privileges. Run this\n" +
        "# ELEVATED (right-click install-watchdog.cmd -> Run as administrator) if the harness\n" +
        "# reported \"Access is denied\" creating the task itself.\n" +
        "$ErrorActionPreference = 'Stop'\n" +
        "$name = '" + TaskName + "'\n" +
        "$wd = '" + PsQuote(watchdogPath) + "'\n" +
        "$user = \"$env:USERDOMAIN\\$env:USERNAME\"\n" +
        "$action = New-ScheduledTaskAction -Execute 'powershell.exe' -Argument \"-NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File `\"$wd`\"\"\n" +
        "$triggers = @((New-ScheduledTaskTrigger -AtStartup), (New-ScheduledTaskTrigger -AtLogOn -User $user))\n" +
        "$settings = New-ScheduledTaskSettingsSet -RestartCount 999 -RestartInterval (New-TimeSpan -Minutes 1) -StartWhenAvailable -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -MultipleInstances IgnoreNew -ExecutionTimeLimit ([TimeSpan]::Zero)\n" +
        "$principal = New-ScheduledTaskPrincipal -UserId $user -LogonType Interactive -RunLevel Highest\n" +
        "Register-ScheduledTask -TaskName $name -Action $action -Trigger $triggers -Settings $settings -Principal $principal -Force | Out-Null\n" +
        "Write-Output ('installed ' + $name)\n";

    /// <summary>The .cmd the Operator right-clicks → Run as administrator when the harness
    /// lacked the rights: it runs the installer elevated.</summary>
    public static string CmdWrapper(string installPs1Path) =>
        "@echo off\r\n" +
        "rem Run this AS ADMINISTRATOR (right-click -> Run as administrator) to install the\r\n" +
        "rem " + TaskName + " keep-alive scheduled task when the harness was denied (fleet task c96de7ae).\r\n" +
        "powershell -NoProfile -ExecutionPolicy Bypass -File \"" + installPs1Path + "\"\r\n" +
        "echo.\r\n" +
        "pause\r\n";

    /// <summary>The exact command the strip shows for the no-privilege case — run it in an
    /// ELEVATED PowerShell/terminal to create the task.</summary>
    public static string ElevatedCommand(string installPs1Path) =>
        "powershell -NoProfile -ExecutionPolicy Bypass -File \"" + installPs1Path + "\"";

    // Single-quoted PowerShell literal: double any embedded single quote.
    private static string PsQuote(string s) => (s ?? "").Replace("'", "''");
}
